# Generated by Django 4.1 on 2022-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="first_name", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.TextField(),
        ),
    ]
