# Generated by Django 4.1 on 2022-08-08 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="isue_id", new_name="issue_id",
        ),
        migrations.RenameField(
            model_name="contributor", old_name="project_pk", new_name="project_id",
        ),
        migrations.RenameField(
            model_name="contributor", old_name="user_pk", new_name="user_id",
        ),
        migrations.AlterUniqueTogether(
            name="contributor", unique_together={("user_id", "project_id")},
        ),
    ]
