# Generated by Django 4.1 on 2022-08-30 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("projects", "0002_rename_isue_id_comment_issue_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors_users",
            field=models.ManyToManyField(
                related_name="contributors_users",
                through="projects.Contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
