# Generated by Django 4.1 on 2022-09-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_contributors_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="description",
            field=models.TextField(max_length=8192),
        ),
    ]
