# Generated by Django 4.1 on 2022-09-08 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_first_name_alter_user_last_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_alter_comment_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="contributors_users",),
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                through="projects.Contributor", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor_project",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributor_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="author_user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
