# Generated by Django 4.1 on 2022-09-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_contributors_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue", name="desc", field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(max_length=8192),
        ),
    ]
