# Generated by Django 4.1 on 2022-09-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_issue_desc_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue", name="desc", field=models.CharField(max_length=8192),
        ),
    ]
